//
//  ViewController.swift
//  CinemaApp
//
//  Created by Dmitry Anatolievich on 11.09.2020.
//  Copyright © 2020 Dmitry Anatolievich. All rights reserved.
//

import UIKit
class ViewController: UIViewController {
    @IBOutlet weak var backgroundView: UIImageView!
    @IBOutlet var filmsButton: UIButton!
    @IBOutlet var serialsButton: UIButton!
    @IBOutlet var cartoonsButton: UIButton!
    
    override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        configBtns()
    }
    var films: [MovieModel] = [
        MovieModel(title: "Iron Man 2",
                   imageName: "iron man 2",
                   filmNameLabel: "Iron Man 2",
                   filmIV: "iron man",
                   yearLabel: "Год: 2008",
                   genreLabel: "Жанр: Боевик,\nПриключения",
                   producerLabel: "Режиссер: Джон Фавро",
                   filmDescriptionText: "Промышленник-миллиардер гениальный изобретатель Тони Старк попадает в плен к Афганским террористам, которые хотят, чтобы он изготовил оружие массового поражения. Вместо этого, используя свой ум и фантазию, Тони конструирует высокотехнологичный железный костюм и спасается бегством. Однако по возвращению он узнаёт о страшном заговоре в Совете директоров своей фирмы. Мирным путем проблемы решать Старк не собирается, поэтому он использует своё новое изобретение.",
                   filmNameLbl: "Iron Man 2",
                   ratingLabel: "9.5",
                   starIV: "star",
                   oneStarIV: "goldStar",
                   twoStarsIV: "goldStar",
                   threeStarsIV: "goldStar",
                   fourStarsIV: "goldStar",
                   fiveStarsIV: "greyStar",
                   castLabel: "В ролях",
                   rateLabel: "Оцените фильм",
                   leftActorIV: "RDJr",
                   rightActorIV: "GP",
                   leftActorNameLabel: "Роберт Дауни младший",
                   rightActorNameLabel: "Гвинет\nПэлтроу"),
        MovieModel(title: "Spider-man",
                   imageName: "spiderman",
                   filmNameLabel: "Spider-man",
                   filmIV: "spiderman",
                   yearLabel: "Год: 2002",
                   genreLabel: "Жанр: Боевик,\nПриключения",
                   producerLabel: "Режиссер: Марк Уэбб",
                   filmDescriptionText: "В детстве Питер Паркер был оставлен своими родителями, и поэтому воспитывался дядей и тётей. Шли годы, Питер был обычным примерным школьником, подвергался нападкам хулиганов и был влюблён в свою одноклассницу Гвен Стэйси, которая сама втайне отвечала ему взаимностью. Но после укуса генетически изменённого паука, Питер получает невероятные сверхспособности и его жизнь меняется навсегда.",
                   filmNameLbl: "Spider-man",
                   ratingLabel: "9.7",
                   starIV: "goldStar",
                   oneStarIV: "goldStar",
                   twoStarsIV: "goldStar",
                   threeStarsIV: "goldStar",
                   fourStarsIV: "goldStar",
                   fiveStarsIV: "greyStar",
                   castLabel: "В ролях",
                   rateLabel: "Оцените фильм",
                   leftActorIV: "AG",
                   rightActorIV: "ES",
                   leftActorNameLabel: "Эндрю Гарфилд",
                   rightActorNameLabel: "Эмма\nСтоун"),
        MovieModel(title: "Тор 2",
                   imageName: "tor",
                   filmNameLabel: "Тор 2",
                   filmIV: "tor",
                   yearLabel: "Год: 2013",
                   genreLabel: "Жанр: Боевик,\nПриключения",
                   producerLabel: "Режиссер: Алан\nТейлор",
                   filmDescriptionText: "Тору предстоит сразиться за спасение Земли и Девяти Миров от таинственного врага из времен, предшествовавших возникновению вселенной. После событий «Тора» и «Мстителей» главный герой борется за восстановление порядка в космосе, но древняя раса во главе с мстительным Малекитом возвращается, чтобы погрузить вселенную обратно во тьму. Столкнувшись с врагом, которому не способен противостоять ни Один, ни весь Асгард, Тор отправляется в самое рискованное путешествие, которое воссоединит его с Джейн Фостер с Земли и заставит пожертвовать всем ради спасения вселенной.",
                   filmNameLbl: "Тор 2",
                   ratingLabel: "8.9",
                   starIV: "goldStar",
                   oneStarIV: "goldStar",
                   twoStarsIV: "goldStar",
                   threeStarsIV: "goldStar",
                   fourStarsIV: "goldStar",
                   fiveStarsIV: "greyStar",
                   castLabel: "В ролях",
                   rateLabel: "Оцените фильм",
                   leftActorIV: "CH",
                   rightActorIV: "NP",
                   leftActorNameLabel: "Крис Хэмсворт",
                   rightActorNameLabel: "Натали\nПортман"),
        MovieModel(title: "Venom",
                   imageName: "venom",
                   filmNameLabel: "Venom",
                   filmIV: "venom",
                   yearLabel: "Год: 2018",
                   genreLabel: "Жанр: Боевик,\nПриключения",
                   producerLabel: "Режиссер: Рубен\nФлейшер",
                   filmDescriptionText: "В центре сюжета — Веном, один из самых известных антигероев вселенной Человека-паука. Это симбиот, разумное существо инопланетного происхождения, которое вселяется в тело Эдди Брока.Жизнь талантливого журналиста Эдди, сломленного из-за увольнения с работы, а также из-за расставания со своей возлюбленной, кардинально меняется после того, как он случайно 'объединяется' с коварным инопланетным пришельцем, наделившим его различными суперспособностями...",
                   filmNameLbl: "Venom",
                   ratingLabel: "9.6",
                   starIV: "goldStar",
                   oneStarIV: "goldStar",
                   twoStarsIV: "goldStar",
                   threeStarsIV: "goldStar",
                   fourStarsIV: "goldStar",
                   fiveStarsIV: "greyStar",
                   castLabel: "В ролях",
                   rateLabel: "Оцените фильм",
                   leftActorIV: "TH",
                   rightActorIV: "MW",
                   leftActorNameLabel: "Том Харди",
                   rightActorNameLabel: "Мишель\nУильямс")
    ]
    
    var series: [MovieModel] = [
        MovieModel(title: "Игра престолов",
                   imageName: "GoT",
                   filmNameLabel: "Игра престолов",
                   filmIV: "GoT",
                   yearLabel: "Год: 2011",
                   genreLabel: "Драма,фэнтези",
                   producerLabel: "Режиссер: Дэвид\nБениофф",
                   filmDescriptionText: "Действие «Игры престолов» происходит в вымышленном мире, напоминающем средневековую Европу. В сериале одновременно действует множество персонажей и развивается несколько сюжетных линий. Основных сюжетных арок три: первая посвящена борьбе нескольких влиятельных домов за Железный Трон Семи Королевств либо за независимость от него; вторая — потомку свергнутой династии правителей, принцессе-изгнаннице, планирующей вернуть престол; третья — древнему братству, охраняющему государство от угроз с севера.",
                   filmNameLbl: "Игра престолов",
                   ratingLabel: "8.9",
                   starIV: "goldStar",
                   oneStarIV: "goldStar",
                   twoStarsIV: "goldStar",
                   threeStarsIV: "goldStar",
                   fourStarsIV: "goldStar",
                   fiveStarsIV: "greyStar",
                   castLabel: "В ролях",
                   rateLabel: "Оцените сериал",
                   leftActorIV: "KH",
                   rightActorIV: "EK",
                   leftActorNameLabel: "Кит\nХэрингтон",
                   rightActorNameLabel: "Эмили\nКларк"),
        MovieModel(title: "Острые козырьки",
                   imageName: "peaky blinders",
                   filmNameLabel: "Острые козырьки",
                   filmIV: "peaky blinders",
                   yearLabel: "Год: 2013",
                   genreLabel: "Драма,\nкриминал",
                   producerLabel: "Режиссер: Стивен\nНайт",
                   filmDescriptionText: "Бирмингем, 1920-е годы. С войны возвращаются члены банды «Острые козырьки» — братья Шелби. Старшим в семье является Артур Шелби (Пол Андерсон), который представляется всем в качестве главаря банды. Однако все дела ведёт Томас Шелби (Киллиан Мёрфи) — средний брат, ведь именно он главарь группировки. Томас всеми силами старается легализовать семейный бизнес. Кровных братьев Шелби четверо — Артур, Томас, Джон и Финн Шелби, однако членов банды «Острых козырьков» намного больше.",
                   filmNameLbl: "Острые козырьки",
                   ratingLabel: "8.8",
                   starIV: "goldStar",
                   oneStarIV: "goldStar",
                   twoStarsIV: "goldStar",
                   threeStarsIV: "goldStar",
                   fourStarsIV: "goldStar",
                   fiveStarsIV: "greyStar",
                   castLabel: "В ролях",
                   rateLabel: "Оцените сериал",
                   leftActorIV: "KM",
                   rightActorIV: "HM",
                   leftActorNameLabel: "Киллиан Мёрфи",
                   rightActorNameLabel: "Хелен\nМакКрори"),
        MovieModel(title: "Во все тяжкие",
                   imageName: "BB",
                   filmNameLabel: "Во все тяжкие",
                   filmIV: "BB",
                   yearLabel: "Год: 2008",
                   genreLabel: "Криминальная драмма",
                   producerLabel: "Режиссер: Винс\nГиллиган",
                   filmDescriptionText: "На протяжении пяти сезонов, состоящих из 62 эпизодов, показана история Уолтера Уайта, школьного учителя, у которого диагностировали неоперабельный рак лёгких. Вместе со своим бывшим учеником Джесси Пинкманом он начинает производить и продавать метамфетамин, чтобы обеспечить финансовое будущее своей семьи.",
                   filmNameLbl: "Во все тяжкие",
                   ratingLabel: "9.5",
                   starIV: "goldStar",
                   oneStarIV: "goldStar",
                   twoStarsIV: "goldStar",
                   threeStarsIV: "goldStar",
                   fourStarsIV: "goldStar",
                   fiveStarsIV: "greyStar",
                   castLabel: "В ролях",
                   rateLabel: "Оцените сериал",
                   leftActorIV: "BK",
                   rightActorIV: "AP",
                   leftActorNameLabel: "Брайан Крэнстон",
                   rightActorNameLabel: "Аарон\nПол"),
        MovieModel(title: "Королевство",
                   imageName: "kingdom",
                   filmNameLabel: "Королевство",
                   filmIV: "kingdom",
                   yearLabel: "Год: 2014",
                   genreLabel: "Драма",
                   producerLabel: "Режиссер: Майкл\nМоррис",
                   filmDescriptionText: "Адреналиновая драма о силе духа. Алви и Лиза владеют тренажерным залом, но дела идут далеко не блестяще. Вся надежда на их сына, талантливого бойца, у которого явно есть перспективы, однако сложная обстановка в семье может все разрушить…Особенно при условии, что в жизни Лизы снова появляется ее экс-бойфренд, бывший чемпион ММА. Энергия и достоверность — «Королевство» зацепит не только фанатов спорта, но и любителей цепких семейных драм без лишних сантиментов.",
                   filmNameLbl: "Королевство",
                   ratingLabel: "8.5",
                   starIV: "goldStar",
                   oneStarIV: "goldStar",
                   twoStarsIV: "goldStar",
                   threeStarsIV: "goldStar",
                   fourStarsIV: "goldStar",
                   fiveStarsIV: "greyStar",
                   castLabel: "В ролях",
                   rateLabel: "Оцените сериал",
                   leftActorIV: "FG",
                   rightActorIV: "JT",
                   leftActorNameLabel: "Фрэнк Грилло",
                   rightActorNameLabel: "Джонатан\nТакер")
    ]
    
    var cartoons: [MovieModel] = [
        MovieModel(title: "Симпсоны",
                   imageName: "simpsons",
                   filmNameLabel: "Симпсоны",
                   filmIV: "simpsons",
                   yearLabel: "Год: 1989",
                   genreLabel: "Комедия",
                   producerLabel: "Режиссер: Мэтт\nГрейнинг",
                   filmDescriptionText: "Мультсериал в сатирическом ключе показывает жизнь семейства Симпсонов и других жителей вымышленного городка Спрингфилд, высмеивая многие клише и стереотипы, в частности — стиль жизни «среднего американца», особенности мировых культур в целом, знаменитостей и даже само телевидение и телеканал «Fox». Сериал не стесняется затрагивать такие скользкие вопросы, как политика и религия: в частности, поднимались темы однополых браков, борьбы дарвинистов и креационистов, войны в Ираке, ювенальной юстиции, политкорректности, феминизма, права граждан на оружие, легализации наркотиков и т.п.",
                   filmNameLbl: "Симпсоны",
                   ratingLabel: "8.5",
                   starIV: "goldStar",
                   oneStarIV: "goldStar",
                   twoStarsIV: "goldStar",
                   threeStarsIV: "goldStar",
                   fourStarsIV: "goldStar",
                   fiveStarsIV: "greyStar",
                   castLabel: "В ролях",
                   rateLabel: "Оцените мультфильм",
                   leftActorIV: "GS",
                   rightActorIV: "MS",
                   leftActorNameLabel: "Гомер Симпсон",
                   rightActorNameLabel: "Мардж\nСимпсон"),
        MovieModel(title: "Котопес",
                   imageName: "catdog",
                   filmNameLabel: "Котопес",
                   filmIV: "catdog",
                   yearLabel: "Год: 1998",
                   genreLabel: "Комедия,\nПриключения",
                   producerLabel: "Режиссер: Питер\nХэннан",
                   filmDescriptionText: "Кошка и собака прекрасно уживаются вместе, если это Котопес – два животных в одном теле. Разница характеров и конфликт интересов отступают на второй план перед большой дружбой на всю жизнь! Популярный комедийный мультсериал родом из конца 1990-х, примиряющий противоположности, но разделивший зрителей на два лагеря. А вы готовы подружиться к Котопсом?",
                   filmNameLbl: "Котопес",
                   ratingLabel: "6.5",
                   starIV: "goldStar",
                   oneStarIV: "goldStar",
                   twoStarsIV: "goldStar",
                   threeStarsIV: "goldStar",
                   fourStarsIV: "goldStar",
                   fiveStarsIV: "greyStar",
                   castLabel: "В ролях",
                   rateLabel: "Оцените мультфильм",
                   leftActorIV: "cat",
                   rightActorIV: "dog",
                   leftActorNameLabel: "Кот",
                   rightActorNameLabel: "Пёс"),
        MovieModel(title: "Король-шаман",
                   imageName: "shaman king",
                   filmNameLabel: "Король-шаман",
                   filmIV: "shaman king",
                   yearLabel: "Год: 2004",
                   genreLabel: "Приключения,\nФантастика",
                   producerLabel: "Режиссер: Сэйдзи\nМидзусима",
                   filmDescriptionText: "Каждые 500 лет Звезда Судьбы, Лаго, проносится по небу, оповещая всех шаманов мира о том, что Великий Турнир Шаманов начался. Но Звезду Судьбы всегда сопровождает Раго — звезда, несущая миру разрушение и хаос. На Турнире и определяется Шаман, достойный объединения с Королём Духов — духом всего сущего, он может как спасти мир, так и уничтожить его. Шаманы способны видеть духов и сражаться вместе с ними как единое целое. Цель Турнира заключается в том, что шаман, который прошёл все испытания и бои, становится Королём Шаманов, объединяется с Королём Духов — величайшим и сильнейшим духом в мире, — и становится настолько могущественным, что может управлять всей жизнью на Земле.",
                   filmNameLbl: "Король-шаман",
                   ratingLabel: "8.2",
                   starIV: "goldStar",
                   oneStarIV: "goldStar",
                   twoStarsIV: "goldStar",
                   threeStarsIV: "goldStar",
                   fourStarsIV: "goldStar",
                   fiveStarsIV: "greyStar",
                   castLabel: "В ролях",
                   rateLabel: "Оцените мультфильм",
                   leftActorIV: "YOA",
                   rightActorIV: "AA",
                   leftActorNameLabel: "Йо Асакура",
                   rightActorNameLabel: "Анна\nАсакура"),
        MovieModel(title: "Эй,Арнольд",
                   imageName: "hey,arnold",
                   filmNameLabel: "Эй,Арнольд",
                   filmIV: "hey,arnold",
                   yearLabel: "Год: 1996",
                   genreLabel: "Комедия,\nПриключения",
                   producerLabel: "Режиссер: Крэйг\nБартлетт",
                   filmDescriptionText: "Главный герой сериала — 9-летний школьник Арнольд, живущий со своими дедушкой Филом и бабушкой Гертрудой по прозвищу Пуки в пансионе «Сансет-Армз» (Sunset Arms), владельцами которого они являются. Его родители Стелла (врач) и Майлз (этнограф) пропали без вести, когда Арнольду исполнился год — они принимали участие в операции по спасению таинственного племени Зеленоглазых в далёкой стране, судя по всему, в Мексике.Сюжет сериала составляют школьные приключения Арнольда и его друзей, истории, происходящие с жильцами пансиона, которым владеет его семья. Особое место занимает история тайной любви Хельги к Арнольду, в которой она никак не может ему признаться, а также борьба с возникающими у её отца бизнес-идеями, так или иначе угрожающими тихому и мирному существованию города.",
                   filmNameLbl: "Эй,Арнольд",
                   ratingLabel: "7.4",
                   starIV: "goldStar",
                   oneStarIV: "goldStar",
                   twoStarsIV: "goldStar",
                   threeStarsIV: "goldStar",
                   fourStarsIV: "goldStar",
                   fiveStarsIV: "greyStar",
                   castLabel: "В ролях",
                   rateLabel: "Оцените мультфильм",
                   leftActorIV: "AS",
                   rightActorIV: "HP",
                   leftActorNameLabel: "Арнольд Шортман",
                   rightActorNameLabel: "Хельга\nПатаки"),
    ]
    
    private func configBtns() {
        filmsButton.addBorderAndShadowToTitle()
        serialsButton.addBorderAndShadowToTitle()
        cartoonsButton.addBorderAndShadowToTitle()
    }
    
    @IBAction func filmsButtonAction(_ sender: Any) {
        guard let controller = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "secondVC") as? SecondViewController else { return }
        controller.setModel(films)
        controller.titleText = "Фильмы"
        self.navigationController?.pushViewController(controller, animated: true)
    }
    
    @IBAction func serialsButtonAction(_ sender: Any) {
        guard let controller = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "secondVC") as? SecondViewController else { return }
        controller.setModel(series)
        controller.titleText = "Сериалы"
        self.navigationController?.pushViewController(controller, animated: true)
    }
    
    @IBAction func cartoonsButtonAction(_ sender: Any) {
        guard let controller = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "secondVC") as? SecondViewController else { return }
        controller.setModel(cartoons)
        controller.titleText = "Мультфильмы"
        self.navigationController?.pushViewController(controller, animated: true)
    }
}


